
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spypahtest.duckdns.org
  namespace: monitoring
spec:
  dnsNames:
  - 'spypahtest.duckdns.org'
  - '*.spypahtest.duckdns.org'
  issuerRef:
    name: cert-manager-webhook-duckdns-production
    kind: ClusterIssuer
  secretName: spypahtest.duckdns.org-tls